#!/bin/bash

while true
do

# Logo

echo "========================================================================================================================"
curl -s https://raw.githubusercontent.com/StakeTake/script/main/logo.sh | bash
echo "========================================================================================================================"

# Menu

PS3='Select an action: '
options=(
"Install Node"
"Check Log"
"Check balance"
"Request tokens in discord"
"Create Validator"
"Exit")
select opt in "${options[@]}"
do
case $opt in

"Install Node")
echo "============================================================"
echo "Install start"
echo "============================================================"
echo "Setup NodeName:"
echo "============================================================"
read NODENAME
echo "============================================================"
echo "Setup WalletName:"
echo "============================================================"
read WALLETNAME
echo export NODENAME=${NODENAME} >> $HOME/.bash_profile
echo export WALLETNAME=${WALLETNAME} >> $HOME/.bash_profile
echo export CHAIN_ID="ollo-testnet-0" >> $HOME/.bash_profile
echo export PROJECT=ollo >> $HOME/.bash_profile
source ~/.bash_profile

#UPDATE APT
sudo apt update && sudo apt upgrade -y
sudo apt install curl tar wget clang pkg-config libssl-dev jq build-essential bsdmainutils git make ncdu gcc git jq chrony liblz4-tool -y

#INSTALL GO
rm -r /usr/local/go
rm -r /usr/lib/go-1.13
wget https://golang.org/dl/go1.18.3.linux-amd64.tar.gz; \
rm -rv /usr/local/go; \
tar -C /usr/local -xzf go1.18.3.linux-amd64.tar.gz && \
rm -v go1.18.3.linux-amd64.tar.gz && \
echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> ~/.bash_profile && \
source ~/.bash_profile && \
go version

#INSTALL BINARY
rm -rf $HOME/ollo $HOME/.ollo
git clone https://github.com/OLLO-Station/ollo
cd ollo
make install

${PROJECT}d init $NODENAME --chain-id $CHAIN_ID


echo "============================================================"
echo "Be sure to write down the mnemonic!"
echo "============================================================"
#WALLET
${PROJECT}d keys add $WALLETNAME

${PROJECT}d unsafe-reset-all --home $HOME/.${PROJECT}
rm $HOME/.${PROJECT}/config/genesis.json
curl http://ollo.stake-take.com:16657/genesis | jq .result.genesis > $HOME/.${PROJECT}/config/genesis.json
wget -O $HOME/.${PROJECT}/config/addrbook.json "https://raw.githubusercontent.com/StakeTake/guidecosmos/main/ollo/ollo-testnet-0/addrbook.json"

SEEDS=""
PEERS=""; \
sed -i.bak -e "s/^seeds *=.*/seeds = \"$SEEDS\"/; s/^persistent_peers *=.*/persistent_peers = \"$PEERS\"/" $HOME/.${PROJECT}/config/config.toml


# config pruning
indexer="null"
pruning="custom"
pruning_keep_recent="100"
pruning_keep_every="0"
pruning_interval="10"

sed -i -e "s/^indexer *=.*/indexer = \"$indexer\"/" $HOME/.${PROJECT}/config/config.toml
sed -i -e "s/^pruning *=.*/pruning = \"$pruning\"/" $HOME/.${PROJECT}/config/app.toml
sed -i -e "s/^pruning-keep-recent *=.*/pruning-keep-recent = \"$pruning_keep_recent\"/" $HOME/.${PROJECT}/config/app.toml
sed -i -e "s/^pruning-keep-every *=.*/pruning-keep-every = \"$pruning_keep_every\"/" $HOME/.${PROJECT}/config/app.toml
sed -i -e "s/^pruning-interval *=.*/pruning-interval = \"$pruning_interval\"/" $HOME/.${PROJECT}/config/app.toml



tee $HOME/${PROJECT}d.service > /dev/null <<EOF
[Unit]
Description=${PROJECT}
After=network.target
[Service]
Type=simple
User=$USER
ExecStart=$(which ${PROJECT}d) start
Restart=on-failure
RestartSec=10
LimitNOFILE=65535
[Install]
WantedBy=multi-user.target
EOF

sudo mv $HOME/${PROJECT}d.service /etc/systemd/system/

# start service
sudo systemctl daemon-reload
sudo systemctl enable ${PROJECT}d
sudo systemctl restart ${PROJECT}d

break
;;

"Check Log")

journalctl -u ${PROJECT}d -f -o cat

break
;;


"Check balance")
${PROJECT}d q bank balances $(${PROJECT}d keys show $WALLETNAME -a --bech acc)
break
;;

"Create Validator")
${PROJECT}d tx staking create-validator \
  --amount 1000000 \
  --from $WALLETNAME \
  --commission-max-change-rate "0.05" \
  --commission-max-rate "0.10" \
  --commission-rate "0.05" \
  --min-self-delegation "1" \
  --pubkey $(${PROJECT}d tendermint show-validator) \
  --moniker $NODENAME \
  --chain-id $CHAIN_ID \
  --gas 300000 \
  -y
break
;;

"Request tokens in discord")
echo "========================================================================================================================"
echo "In order to receive tokens, you need to go to the Discord server
and request tokens in the validator channel"
echo "========================================================================================================================"

break
;;

"Exit")
exit
;;
*) echo "invalid option $REPLY";;
esac
done
done
